language: go

go: 
  - 1.8.3

notifications:
  email: false

gobuild_args: -x -v --ldflags '-extldflags "-static"'

env:
  global:
    - GIMME_OS=linux
  matrix:
    - GIMME_ARCH=amd64
    - GIMME_ARCH=386
