language: go

go: 
  - 1.8.3

notifications:
  email: false

gobuild_args: &gobuildargs -x -v --ldflags '-extldflags "-static"'

env:
  global:
    - GIMME_ARCH=amd64
    - GIMME_OS=linux

after_success:
  - go build -x -v --ldflags '-extldflags "-static"'
  - ls -la journey
  - ldd journey
